ALTER TABLE users
  ALTER COLUMN date_modified DROP NOT NULl,
  ALTER COLUMN date_modified DROP DEFAULT;

ALTER TABLE posts
  ALTER COLUMN date_modified DROP NOT NULL,
  ALTER COLUMN date_modified DROP DEFAULT;